import type { UserProfile } from '@/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

export const mockAides: UserProfile[] = [
  {
    uid: '1',
    prenom: 'Awa',
    nom: 'Traoré',
    telephoneWhatsApp: '76123456',
    photo: PlaceHolderImages.find(p => p.id === 'person1'),
    quartier: 'ACI 2000',
    age: 28,
    typeService: ['Ménage', 'Repassage'],
    disponible: true,
    disponibilite: 'Lundi à Vendredi, 8h-17h',
    experience: 5,
    description: 'Aide ménagère expérimentée, ponctuelle et sérieuse. Je suis disponible pour un service de qualité.',
    rating: 4.5,
    reviewCount: 12,
  },
  {
    uid: '2',
    prenom: 'Fatoumata',
    nom: 'Diarra',
    telephoneWhatsApp: '78901234',
    photo: PlaceHolderImages.find(p => p.id === 'person2'),
    quartier: 'Badalabougou',
    age: 35,
    typeService: ['Ménage complet', 'Cuisine'],
    disponible: false,
    disponibilite: 'Contacter pour disponibilité',
    experience: 10,
    description: 'Spécialiste de la cuisine malienne et du ménage complet. Je garantis un travail impeccable.',
    rating: 4.8,
    reviewCount: 25,
  },
  {
    uid: '3',
    prenom: 'Mariam',
    nom: 'Coulibaly',
    telephoneWhatsApp: '65432109',
    photo: PlaceHolderImages.find(p => p.id === 'person3'),
    quartier: 'Hippodrome',
    age: 22,
    typeService: ['Garde d\'enfants', 'Ménage'],
    disponible: true,
    disponibilite: 'Week-ends et soirs',
    experience: 2,
    description: 'Étudiante, douce et patiente avec les enfants. Expérience en baby-sitting et entretien de la maison.',
    rating: 4.2,
    reviewCount: 5,
  },
    {
    uid: '4',
    prenom: 'Bintou',
    nom: 'Keita',
    telephoneWhatsApp: '70112233',
    photo: PlaceHolderImages.find(p => p.id === 'person4'),
    quartier: 'Sébénikoro',
    age: 40,
    typeService: ['Cuisine', 'Courses'],
    disponible: true,
    disponibilite: 'Matinées (Lundi, Mercredi, Vendredi)',
    experience: 15,
    description: 'Cuisinière hors pair, je peux préparer de délicieux plats pour toute la famille et faire les courses.',
    rating: 5.0,
    reviewCount: 30,
  },
];
